# Generated by Django 5.1.15 on 2026-10-08 01:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PitchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, default=uuid.uuid4, help_text='Unique identifier for the pitch practice run', max_length=64, unique=True)),
                ('deck_name', models.CharField(default='Untitled Pitch Deck', max_length=255)),
                ('target_duration_sec', models.PositiveIntegerField(default=180)),
                ('total_duration_sec', models.PositiveIntegerField(default=0)),
                ('overall_score', models.FloatField(default=0.0)),
                ('overall_score_formatted', models.CharField(default='0.0 / 10', max_length=32)),
                ('status', models.CharField(choices=[('Needs Polish', 'Needs Polish'), ('Solid Contender', 'Solid Contender'), ('Winning Caliber', 'Winning Caliber')], default='Needs Polish', max_length=64)),
                ('margin_note', models.CharField(blank=True, default='', max_length=255)),
                ('margin_target_category', models.CharField(blank=True, default='Idea', max_length=64)),
                ('transcript', models.TextField(blank=True, default='')),
                ('wpm', models.PositiveIntegerField(default=0)),
                ('ai_provider', models.CharField(default='gemini', max_length=32)),
                ('rubric_data', models.JSONField(blank=True, default=list, help_text='5-axis hackathon rubric scores and critiques')),
                ('slide_pacing_data', models.JSONField(blank=True, default=list, help_text='Per-slide duration, pacing share, and overtime alerts')),
                ('filler_words_data', models.JSONField(blank=True, default=list, help_text='Detected filler words count and timestamps')),
                ('strengths_data', models.JSONField(blank=True, default=list, help_text='Bullet points of key pitch strengths')),
                ('improvements_data', models.JSONField(blank=True, default=list, help_text='Actionable feedback for winning caliber')),
                ('judge_questions_data', models.JSONField(blank=True, default=list, help_text='Judge cross-examination questions and founder responses')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pitch Rehearsal Session',
                'verbose_name_plural': 'Pitch Rehearsal Sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
